### ISSUE TITLE
Punishment system

### ISSUE THREAD

**Issue by franciscoatwi** [sirDonovan/Cassius#12]
Banned words are having trouble, and I haven't gotten flooding and other automated punishments to work either.

**Comment by sirDonovan** [comment]
Banned words are words that users can't say server-wide, not words that Cassius will punish for. Did you set <code>Config.allowModeration</code> to <code>true</code>?

**Comment by franciscoatwi** [comment]
yes

**Comment by franciscoatwi** [comment]
it was true and I added banwords in the proper format `['banword1', 'banword2', 'etc']`

**Comment by franciscoatwi** [comment]
How does Cassius respond to them if not punishment?

**Comment by sirDonovan** [comment]
It won't respond to them; they are words that it will not say itself.

**Comment by franciscoatwi** [comment]
Okay, I see, however the flooding moderation was still not working for me.

**Comment by franciscoatwi** [comment]
I dont know what the problem was but it didn't mute after about 10 lines were tested (In a bot testing room on another PS server)

**Comment by HarmanPC** [comment]
![test](https://user-images.githubusercontent.com/29503925/39967185-b1f7f604-56d4-11e8-8625-89c369c844f7.png)
Works fine for me

**Comment by HarmanPC** [comment]
1) Config.allowModeration = true;
2) Bot must have rank % or up.
3) You shouldn't have any rank in the room else it'll not moderate (https://github.com/sirDonovan/Cassius/blob/master/message-parser.js#L318)

**Comment by franciscoatwi** [comment]
I had it set like that, I probably did it wrong. Anyways sorry, just was a concern. I'm closing this
